image: ${docker_registry}redhawk/centos7-evo:latest

stages:
  - trigger

variables:
  # The REDHAWK branch variable tracks the mainline branch from which a topic
  # branch was forked, allowing it to still trigger that branch's test pipeline
  redhawk_branch: 'develop-2.2'
  redhawk_branch_slug: 'develop-2-2'
  # Default to the redhawk branch named in the global variables, which will
  # typically be a develop branch. Feature branches trigger a test pipeline
  # using the develop branch from which they were forked unless overridden here.
  testing_branch: 'bugs/ide-2311'

# Trigger separate tests pipeline
.trigger-common: &trigger-common
  stage: trigger
  dependencies: []
  variables:
    test_ref: "bugs/ide-2311"
  script:
    - curl --insecure -X POST -F ref=$testing_branch
                              -F token=$test_token
                              -F "variables[triggering_ref]=$CI_COMMIT_SHA"
                              -F "variables[triggering_ref_name]=$CI_COMMIT_REF_NAME"
                              -F "variables[triggering_ref_slug]=$CI_COMMIT_REF_SLUG"
                              -F "variables[tests_ref]=$test_ref"
                              -F "variables[p2_repo_location]=$CI_COMMIT_REF_SLUG"
                              $test_url

# For bug/feature branches, require the developer to manually trigger the tests
# Use commit_ref_slug as redhawk_version to reuse the docker image created previously
test:branch:
  <<: *trigger-common
  only:
    - branches
  except:
    - master
    - /^develop.*$/

# For develop branches, automatically trigger test pipeline
test-trigger:develop:
  <<: *trigger-common
  only:
    - /^develop.*$/

test:release:
  stage: trigger
  dependencies: []
  variables:
    test_ref: '2.2.4-rc1'
  script:
    - curl --insecure -X POST -F ref=$redhawk_branch
                              -F token=$test_token
                              -F "variables[triggering_ref]=$CI_COMMIT_SHA"
                              -F "variables[triggering_ref_name]=$CI_COMMIT_REF_NAME"
                              -F "variables[output_name]=$CI_COMMIT_REF_NAME"
                              -F "variables[tests_ref]=$CI_COMMIT_REF_NAME"
                              -F "variables[p2_repo_location]=$CI_COMMIT_REF_SLUG"
                              $test_url
  only:
    - tags
  except:
    - /^(\d+\.)?(\d+)?(\.\d+)$/

